name: fav_test_task
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  svg_image: ^0.0.5
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  flutter_gen: ^5.10.0
  flutter_gen_runner: ^5.10.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/moon.svg
    - assets/svg/sun.svg
    - assets/svg/search.svg
    - .env
